<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\city.glb -T --draco /draco/
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/city-transformed.glb', { dracoLoader: useDraco() })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Mesh1_Group1_Model.geometry}
      material={gltf.materials['FrontColor.001']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh2_Group2_Model.geometry}
      material={gltf.materials['FrontColor.001']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh3_Group3_Model.geometry}
      material={gltf.materials['FrontColor.001']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh4_Group4_Model.geometry}
      material={gltf.materials['FrontColor.001']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh5_Model.geometry}
      material={gltf.materials['FrontColor.001']}
      rotation={[Math.PI / 2, 0, 0]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
